version: "3.8"

services:
  web:
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/src/app
    environment:
      - GO_ENV=${GO_ENV}
    command: ${COMMAND}
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
